site_name: Tracebundy
pages:
    - Home : 'index.md'
    - MongoDB :
        - Query : 'MongoDB-Query.md'
        - MongoDB&Raft : 'MongoDB-Raft.md'
        # - Pipeline : 'MongoDB-Pipeline.md'
    - MySQL :
        - Select : 'MySQL-Select.md'
    - LevelDB :
        - Read : 'leveldb-read-flow.md'
        - Write : 'leveldb-write-flow.md'
    - About : 'about.md'
theme: mkdocs
# theme: readthedocs
